### ISSUE TITLE
custom logfile location for clients

### ISSUE THREAD

**Issue by cashmerethief** [urbanware-org/wideredist#6]
would it be possible to manually set the logfile location?

**Comment by urbanware-org** [comment]
This should not be a problem at all. I just created a corresponding [branch](https://github.com/urbanware-org/wideredist/tree/custom-logfile-location) for that request.

**Comment by urbanware-org** [comment]
I have added the following options to the client-side config file:

```ini
[Logs]
LogFilePath = "C:\Tools\Defender"
LogFileName = "RecentUpdate.log"
IncludeHostname = 0
```

In case you want to store the log files of multiple systems in a central place (e.g. a network share), I also added the `IncludeHostname` option. For example, if your computer name is `Foobar` and the option is set to `1`, the log file name will be renamed to `RecentUpdate_Foobar.log`.

Does this satisfy your needs?

**Comment by cashmerethief** [comment]
Yes! Thank you very much for the fast implementation.

**Comment by urbanware-org** [comment]
You're welcome!

**Comment by urbanware-org** [comment]
Added in version **1.4.3**.
